//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSale
    {
        public int saleId { get; set; }
        public Nullable<int> saleProduct { get; set; }
        public Nullable<int> saleCustomer { get; set; }
        public Nullable<decimal> salePreis { get; set; }
        public Nullable<System.DateTime> saleDate { get; set; }
    
        public virtual TblCustomer TblCustomer { get; set; }
        public virtual TblProduct TblProduct { get; set; }
    }
}
